# Generated by Django 3.2.10 on 2021-12-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app_redes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Blog Aplicações em Redes', max_length=255),
        ),
    ]
