# Generated by Django 4.0 on 2022-01-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app_redes', '0007_post_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
